input_=input("enter the A B C values: ")
in_list=input_.split(" ")
a=float(in_list[0])
b=float(in_list[1])
c=float(in_list[2])
bsq=(b*b)
print(bsq)
ac4=(a*c*4)
print(ac4)
val=(bsq-ac4)
print(val)
from math import sqrt
sqrt_= ((abs(val))**(1/2))
print(sqrt_)
x1=(((-b)+sqrt_)/(2*a))
x2=(((-b)-sqrt_)/(2*a))
print(round(x1,2))
print(round(x1,2))